### ISSUE TITLE
Proper deactivating of abilities in the fleet creator

### ISSUE THREAD

**Issue by Nucaranlaeg** [Nucaranlaeg/Ignis-Astrum#3]
Currently, abilities are deactivated (grayed out) if they're not available for a base.  This needs to be extended:

- Abilities should be deactivated if unavailable for ships (none currently in the game; if needed a testing ability can be added).
- Abilities should be deactivated if the ship/base has the maximum and would otherwise be able to obtain said ability.

**Comment by nedbenner** [comment]
This issue has been resolved with the ~"fix de-activation..." branch.
